$(document).ready(function(){
    $('#i11').keyup(function(){
        $('#notDefaultreceiver1').text($('#i11').val());
        console.log($('#i11').val());
        console.log("hello");
    })
    $('#i12').keyup(function(){
        $('#notDefaultreceiver2').text($('#i12').val());
        console.log($('#i12').val());
        console.log("hello");
    })
    $('#i13').keyup(function(){
        $('#notDefaultreceiver3').text($('#i13').val());
        console.log($('#i13').val());
        console.log("hello");
    })
    $('#i21').keyup(function(){
        $('#msg1').text($('#i21').val());
        console.log($('#i11').val());
        console.log("hello");
    })
    $('#i22').keyup(function(){
        $('#msg2').text($('#i22').val());
        console.log($('#i12').val());
        console.log("hello");
    })
    $('#i23').keyup(function(){
        $('#msg3').text($('#i23').val());
        console.log($('#i13').val());
        console.log("hello");
    })
    $('#i31').keyup(function(){
        $('#notDefaultsender1').text($('#i31').val());
        console.log($('#i31').val());
        console.log("hello");
    })
    $('#i32').keyup(function(){
        $('#notDefaultsender2').text($('#i32').val());
        console.log($('#i32').val());
        console.log("hello");
    })
    $('#i33').keyup(function(){
        $('#notDefaultsender3').text($('#i33').val());
        console.log($('#i33').val());
        console.log("hello");
    })
})